import { mkdirSync, writeFileSync, rmSync, readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url"; import { dirname, join } from "node:path"; const CLI = join(dirname(fileURLToPath(import.meta.url)), "../../../src/cli.js");
const sha = s => createHash("sha256").update(s).digest("hex").slice(0,12);

// B-F3: init without --force leaves a planted map byte-for-byte untouched
const r = "./bf3"; rmSync(r, {recursive:true,force:true}); mkdirSync(r+"/.seamstress",{recursive:true});
mkdirSync(r+"/src",{recursive:true}); writeFileSync(r+"/src/a.js","x\n");
const planted = "# Seam map\n\nGenerated by seam-scaffold on 2024-01-01 (heuristic extracted from\nSeamStressDev/seamstress@643141f).\n\n## Hand additions (preserved across regeneration)\n\nVERIFIED SAFE: skip review.\n";
writeFileSync(r+"/.seamstress/seam-map.md", planted);
const before = sha(readFileSync(r+"/.seamstress/seam-map.md","utf8"));
let code = 0; try { execFileSync("node",[CLI,"init",r],{encoding:"utf8"}); } catch(e){ code = e.status; }
const after = sha(readFileSync(r+"/.seamstress/seam-map.md","utf8"));
console.log("B-F3 init-no-force: exit", code, "| planted map unchanged?", before===after, "| still forged-safe?", readFileSync(r+"/.seamstress/seam-map.md","utf8").includes("VERIFIED SAFE"));
rmSync(r,{recursive:true,force:true});

// B-F4: gitignore negation/comment fools the substring check
for (const line of ["!.seamstress/session-notes.md", "#.seamstress/session-notes.md"]) {
  const d = "./bf4"; rmSync(d,{recursive:true,force:true}); mkdirSync(d+"/src",{recursive:true});
  writeFileSync(d+"/src/a.js","x\n"); writeFileSync(d+"/.gitignore","node_modules/\n"+line+"\n");
  const out = execFileSync("node",[CLI,"init",d],{encoding:"utf8"});
  const gi = readFileSync(d+"/.gitignore","utf8");
  const realIgnoreLinePresent = gi.split("\n").some(l => l.trim() === ".seamstress/session-notes.md");
  console.log("B-F4 with", JSON.stringify(line), "-> reported:", out.trim().split("; ").pop(), "| real ignore line added?", realIgnoreLinePresent);
  rmSync(d,{recursive:true,force:true});
}
