// The drift contract: the scaffold heuristic must reproduce the engine
// heuristic's candidate sets exactly on two known inputs. Fixtures were
// generated by running the engine's TypeScript heuristic (see each fixture's
// engineCommit). If this test goes red after a deliberate scaffold change,
// regenerate the fixtures against the engine and record the divergence; a red
// parity test is information, not an obstacle.

import { test } from "node:test";
import assert from "node:assert";
import { readFileSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { scanRepo } from "../src/heuristic/heuristic.js";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");

function loadFixture(name) {
  return JSON.parse(readFileSync(join(here, "fixtures", name), "utf8"));
}

test("parity: scratch-app candidates match the engine fixture (hermetic)", () => {
  const fixture = loadFixture("parity-scratch-app.json");
  const got = scanRepo(join(repoRoot, "validation", "scratch-app"));
  assert.deepStrictEqual(got, fixture.candidates);
});

test("parity: engine repo candidates match the engine fixture (needs the engine checkout)", (t) => {
  const fixture = loadFixture("parity-engine-repo.json");
  const enginePath = process.env.SEAM_ENGINE_PATH ?? join(repoRoot, "..", "seamstress");
  if (!existsSync(enginePath)) {
    t.skip(`SKIPPED: engine repo not found at ${enginePath}; set SEAM_ENGINE_PATH`);
    return;
  }
  let head = "";
  try {
    head = execFileSync("git", ["-C", enginePath, "rev-parse", "--short", "HEAD"], {
      encoding: "utf8",
    }).trim();
  } catch {
    t.skip(`SKIPPED: could not read git HEAD at ${enginePath}`);
    return;
  }
  if (!head.startsWith(fixture.engineCommit)) {
    t.skip(
      `SKIPPED: engine repo at ${head}, fixture pinned to ${fixture.engineCommit}; ` +
        `regenerate the fixture to re-arm this test`,
    );
    return;
  }
  const got = scanRepo(enginePath);
  assert.deepStrictEqual(got, fixture.candidates);
});
